"use client";

import { useId, useState } from "react";

export function MigrationPolicyLab() {
  const id = useId();
  const [budget, setBudget] = useState(20);
  const [complianceShare, setComplianceShare] = useState(50);
  // Illustrative annual accounting, not an empirically estimated policy effect.
  const options = [25, 50, 75].map((share) => calculate(budget, share));
  const result = calculate(budget, complianceShare);
  return <section aria-labelledby={`${id}-title`} className="h-auto rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900">
    <header className="p-5"><p className="eyebrow">Interactive lab / Synthetic data</p><h2 id={`${id}-title`} className="mt-2 text-xl font-semibold">Irregular Migration Policy Lab</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">Which policy mix reduces irregular status while protecting Malaysian public-service capacity?</p><p className="mt-3 rounded-lg bg-indigo-50 p-3 text-xs leading-5 text-indigo-900 dark:bg-indigo-400/10 dark:text-indigo-200">Rohingya displacement is context, not an enforcement criterion. UNHCR documentation does not give immunity from Malaysian law. Refugee protection needs and immigration status require separate assessments.</p></header>
    <div className="border-t border-slate-200 p-5 dark:border-slate-700"><p className="eyebrow">01 / Descriptive · establish the baseline</p><p className="mt-3 text-xs">Illustrative year-end unresolved irregular-status cases</p><p className="mt-2 font-mono text-4xl font-semibold tabular-nums">{result.remaining.toLocaleString("en-US")}</p><p className="mt-3 text-xs leading-6 text-slate-500 dark:text-slate-400">Fixture: 10,000 initial cases + 2,000 potential new cases over one year. These are fictional counts, not estimates of Rohingya or other migrants in Malaysia.</p></div>
    <div className="border-t border-slate-200 p-5 dark:border-slate-700"><p className="eyebrow">02 / Diagnostic · distinguish the mechanisms</p><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt>New irregular cases avoided</dt><dd className="mt-2 font-mono text-xl">{result.prevented}</dd></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt>Lawful status resolutions</dt><dd className="mt-2 font-mono text-xl">{result.resolved}</dd></div></dl><p className="mt-3 text-xs leading-6 text-slate-500 dark:text-slate-400">Employer compliance and anti-smuggling measures address new irregularity. Individual case processing addresses existing status through lawful pathways, eligible resettlement, or safe voluntary return. Registration alone is not counted as resolution.</p></div>
    <div className="border-t border-slate-200 p-5 dark:border-slate-700"><p className="eyebrow">03 / Predictive · compare budget choices</p><label htmlFor={`${id}-budget`} className="mt-4 flex justify-between text-sm">Annual programme budget<span className="font-mono">RM {budget}M</span></label><input id={`${id}-budget`} type="range" min={5} max={40} value={budget} onChange={(e) => setBudget(Number(e.currentTarget.value))} className="h-11 w-full accent-indigo-500" aria-valuetext={`RM ${budget} million`} /><label htmlFor={`${id}-share`} className="mt-3 flex justify-between gap-3 text-sm">Employer compliance / anti-smuggling share<span className="font-mono">{complianceShare}%</span></label><input id={`${id}-share`} type="range" min={0} max={100} step={5} value={complianceShare} onChange={(e) => setComplianceShare(Number(e.currentTarget.value))} className="h-11 w-full accent-indigo-500" aria-valuetext={`${complianceShare} percent; ${100-complianceShare} percent for lawful case resolution`} /><p className="text-xs leading-6">Remaining {100-complianceShare}% funds lawful case resolution.</p><code className="mt-3 block rounded-lg bg-slate-50 p-3 text-[11px] leading-6 dark:bg-slate-950">year_end = 10,000 + 2,000 − avoided_new − resolved_existing</code><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Assumed RM5,000 per avoided new case (maximum 2,000); RM10,000 per resolved existing case (maximum 10,000). Fixed illustrative efficiencies; real effects, eligibility and implementation costs require evaluation.</p></div>
    <div className="border-t border-slate-200 p-5 dark:border-slate-700"><p className="eyebrow">04 / Prescriptive · assess Malaysian outcomes</p><p className="mt-3 text-sm leading-6">Compare public spending, access to clinics for residents, labour standards and case-processing outcomes together. Fewer unresolved statuses do not necessarily mean fewer residents or lower service demand.</p><table className="mt-4 w-full text-left text-xs"><caption className="mb-2 text-left text-slate-500 dark:text-slate-400">Same budget · illustrative allocation comparison</caption><thead><tr><th scope="col" className="py-2">Compliance share</th><th scope="col">Cases remaining</th><th scope="col">Spend / outcome*</th></tr></thead><tbody>{options.map((option) => <tr key={option.share} className="border-t border-slate-200 dark:border-slate-700"><th scope="row" className="py-3 font-medium">{option.share}%</th><td className="font-mono">{option.remaining.toLocaleString("en-US")}</td><td className="font-mono">RM {option.unitCost.toLocaleString("en-US")}</td></tr>)}</tbody></table><p className="mt-2 text-[11px] leading-5 text-slate-500 dark:text-slate-400">*Programme spend divided by avoided plus resolved cases; these outcomes are different and this ratio is not a welfare score.</p><div role="status" className="mt-4 rounded-lg border border-indigo-300 bg-indigo-50 p-4 text-sm leading-6 text-indigo-950 dark:border-indigo-500/40 dark:bg-indigo-500/10 dark:text-indigo-100">Current mix: {result.prevented + result.resolved} fewer unresolved cases than the no-programme fixture. Treat this as a sensitivity exercise, not proof of a best policy.</div><p className="mt-3 text-xs leading-6 text-slate-500 dark:text-slate-400">A real evaluation needs verified migration flows, employer compliance, programme costs, clinic waiting times, and labour-market evidence. No ethnicity-based targeting, individual risk scores, automated removal decisions, or forced-return recommendations are generated.</p><a href="https://www.unhcr.org/my/refugee-fact-check" className="mt-3 inline-block text-xs underline underline-offset-4">UNHCR Malaysia: documentation and legal immunity explained</a></div>
  </section>;
}

function calculate(budget: number, share: number) {
  const prevented = Math.min(2000, Math.floor(budget * 1e6 * share / 100 / 5000));
  const resolved = Math.min(10000, Math.floor(budget * 1e6 * (100-share) / 100 / 10000));
  return { share, prevented, resolved, remaining: 12000-prevented-resolved, unitCost: Math.round(budget * 1e6 / (prevented+resolved)) };
}
